# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(375, 412)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.hideButton = QtWidgets.QCheckBox(self.centralwidget)
        self.hideButton.setGeometry(QtCore.QRect(20, 30, 131, 20))
        self.hideButton.setObjectName("hideButton")
        self.changeText = QtWidgets.QCheckBox(self.centralwidget)
        self.changeText.setGeometry(QtCore.QRect(20, 60, 121, 20))
        self.changeText.setObjectName("changeText")
        self.enlargeFontOnButton = QtWidgets.QCheckBox(self.centralwidget)
        self.enlargeFontOnButton.setGeometry(QtCore.QRect(20, 120, 141, 20))
        self.enlargeFontOnButton.setObjectName("enlargeFontOnButton")
        self.disableButton = QtWidgets.QCheckBox(self.centralwidget)
        self.disableButton.setGeometry(QtCore.QRect(20, 150, 151, 20))
        self.disableButton.setObjectName("disableButton")
        self.paintButton = QtWidgets.QCheckBox(self.centralwidget)
        self.paintButton.setGeometry(QtCore.QRect(20, 90, 171, 20))
        self.paintButton.setObjectName("paintButton")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 180, 231, 141))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setAcceptDrops(False)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 375, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.hideButton.setText(_translate("MainWindow", "Спрятать кнопку"))
        self.changeText.setText(_translate("MainWindow", "Изменить текст"))
        self.enlargeFontOnButton.setText(_translate("MainWindow", "Увеличить шрифт"))
        self.disableButton.setText(_translate("MainWindow", "Сделать неактивной"))
        self.paintButton.setText(_translate("MainWindow", "Перекрасить в красный"))
        self.pushButton.setText(_translate("MainWindow", "Button"))
