# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(630, 617)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dataBase = QtWidgets.QTableWidget(self.centralwidget)
        self.dataBase.setGeometry(QtCore.QRect(0, 40, 631, 551))
        self.dataBase.setObjectName("dataBase")
        self.dataBase.setColumnCount(0)
        self.dataBase.setRowCount(0)
        self.classChoose = QtWidgets.QCheckBox(self.centralwidget)
        self.classChoose.setGeometry(QtCore.QRect(10, 10, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.classChoose.setFont(font)
        self.classChoose.setObjectName("classChoose")
        self.schoolChoose = QtWidgets.QCheckBox(self.centralwidget)
        self.schoolChoose.setGeometry(QtCore.QRect(310, 10, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.schoolChoose.setFont(font)
        self.schoolChoose.setObjectName("schoolChoose")
        self.classNumber = QtWidgets.QComboBox(self.centralwidget)
        self.classNumber.setGeometry(QtCore.QRect(240, 10, 61, 22))
        self.classNumber.setObjectName("classNumber")
        self.schoolNumber = QtWidgets.QComboBox(self.centralwidget)
        self.schoolNumber.setGeometry(QtCore.QRect(540, 10, 81, 22))
        self.schoolNumber.setObjectName("schoolNumber")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.classChoose.setText(_translate("MainWindow", "Фильтр по номеру класса"))
        self.schoolChoose.setText(_translate("MainWindow", "Фильтр по номеру школы"))
