# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(419, 197)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.C = QtWidgets.QPushButton(self.centralwidget)
        self.C.setGeometry(QtCore.QRect(0, 0, 61, 200))
        self.C.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.C.setText("")
        self.C.setObjectName("C")
        self.D = QtWidgets.QPushButton(self.centralwidget)
        self.D.setGeometry(QtCore.QRect(60, 0, 61, 200))
        self.D.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.D.setText("")
        self.D.setObjectName("D")
        self.E = QtWidgets.QPushButton(self.centralwidget)
        self.E.setGeometry(QtCore.QRect(120, 0, 61, 200))
        self.E.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.E.setText("")
        self.E.setObjectName("E")
        self.F = QtWidgets.QPushButton(self.centralwidget)
        self.F.setGeometry(QtCore.QRect(180, 0, 61, 200))
        self.F.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.F.setText("")
        self.F.setObjectName("F")
        self.G = QtWidgets.QPushButton(self.centralwidget)
        self.G.setGeometry(QtCore.QRect(240, 0, 61, 200))
        self.G.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.G.setText("")
        self.G.setObjectName("G")
        self.B = QtWidgets.QPushButton(self.centralwidget)
        self.B.setGeometry(QtCore.QRect(360, 0, 61, 200))
        self.B.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.B.setText("")
        self.B.setObjectName("B")
        self.A = QtWidgets.QPushButton(self.centralwidget)
        self.A.setGeometry(QtCore.QRect(300, 0, 61, 200))
        self.A.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.A.setText("")
        self.A.setObjectName("A")
        self.Cs = QtWidgets.QPushButton(self.centralwidget)
        self.Cs.setGeometry(QtCore.QRect(40, -10, 41, 121))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Cs.setFont(font)
        self.Cs.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(37, 37, 37);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.Cs.setText("")
        self.Cs.setObjectName("Cs")
        self.Ds = QtWidgets.QPushButton(self.centralwidget)
        self.Ds.setGeometry(QtCore.QRect(100, 0, 41, 111))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Ds.setFont(font)
        self.Ds.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(37, 37, 37);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.Ds.setText("")
        self.Ds.setObjectName("Ds")
        self.Fs = QtWidgets.QPushButton(self.centralwidget)
        self.Fs.setGeometry(QtCore.QRect(220, 0, 41, 111))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Fs.setFont(font)
        self.Fs.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(37, 37, 37);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.Fs.setText("")
        self.Fs.setObjectName("Fs")
        self.Gs = QtWidgets.QPushButton(self.centralwidget)
        self.Gs.setGeometry(QtCore.QRect(280, 0, 41, 111))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Gs.setFont(font)
        self.Gs.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(37, 37, 37);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.Gs.setText("")
        self.Gs.setObjectName("Gs")
        self.As = QtWidgets.QPushButton(self.centralwidget)
        self.As.setGeometry(QtCore.QRect(340, 0, 41, 111))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.As.setFont(font)
        self.As.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(37, 37, 37);\n"
"    color:  rgb(255, 255, 255);\n"
"}")
        self.As.setText("")
        self.As.setObjectName("As")
        self.D.raise_()
        self.C.raise_()
        self.E.raise_()
        self.F.raise_()
        self.G.raise_()
        self.B.raise_()
        self.A.raise_()
        self.Cs.raise_()
        self.Ds.raise_()
        self.Fs.raise_()
        self.Gs.raise_()
        self.As.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
